# GitHub Actions workflow for building and deploying the React frontend to Azure Static Web Apps
# Place this file in .github/workflows/frontend-staticwebapp.yml

name: 'Build and Deploy React Frontend'

on:
  push:
    branches: [ main ]
    paths:
      - 'reactappwithgithubcopilotagent.client/**'
      - '.github/workflows/frontend-staticwebapp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'reactappwithgithubcopilotagent.client/**'
      - '.github/workflows/frontend-staticwebapp.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd reactappwithgithubcopilotagent.client
          npm ci

      - name: Build
        run: |
          cd reactappwithgithubcopilotagent.client
          npm run build

      # Azure Static Web Apps Deploy (requires AZURE_STATIC_WEB_APPS_TOKEN secret)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: 'upload'
          app_location: 'reactappwithgithubcopilotagent.client'
          output_location: 'reactappwithgithubcopilotagent.client/dist'
